**Run the following two cells before you begin.**

In [2]:
%autosave 10

Autosaving every 10 seconds

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, roc_curve

%matplotlib inline

**First, import the cleaned data set. Then, select the features from the DataFrame of the case study data.**
    
These features should be: `'LIMIT_BAL'`, `'EDUCATION'`, `'MARRIAGE'`, `'AGE'`, `'PAY_1'`, `'BILL_AMT1'`, `'BILL_AMT2'`, `'BILL_AMT3'`, `'BILL_AMT4'`, `'BILL_AMT5'`, `'BILL_AMT6'`, `'PAY_AMT1'`, `'PAY_AMT2'`, `'PAY_AMT3'`, `'PAY_AMT4'`, `'PAY_AMT5'`, AND `'PAY_AMT6'`.

In [4]:
# Import data set
df=pd.read_csv('cleaned_data.csv')

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month,EDUCATION_CAT,graduate school,high school,others,university
0,798fc410-45c1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,1,university,0,0,0,1
1,8a8c8f3b-8eb4,120000,2,2,2,26,-1,2,0,0,...,1000,1000,0,2000,1,university,0,0,0,1
2,85698822-43f5,90000,2,2,2,34,0,0,0,0,...,1000,1000,1000,5000,0,university,0,0,0,1
3,0737c11b-be42,50000,2,2,1,37,0,0,0,0,...,1200,1100,1069,1000,0,university,0,0,0,1
4,3b7f77cc-dbc0,50000,1,2,1,57,-1,0,-1,0,...,10000,9000,689,679,0,university,0,0,0,1
5,ceae2946-47e4,50000,1,1,2,37,0,0,0,0,...,657,1000,1000,800,0,graduate school,1,0,0,0
6,d3b8ce26-9c89,500000,1,1,2,29,0,0,0,0,...,38000,20239,13750,13770,0,graduate school,1,0,0,0
7,d6e1911b-54d0,100000,2,2,2,23,0,-1,-1,0,...,0,581,1687,1542,0,university,0,0,0,1
8,8421d3b3-2b54,140000,2,3,1,28,0,0,2,0,...,432,1000,1000,1000,0,high school,0,1,0,0
9,62a2fd79-cd90,20000,1,3,2,35,-2,-2,-2,-2,...,0,13007,1122,0,0,high school,0,1,0,0
10,b73c34fc-91cf,200000,2,3,2,34,0,0,2,0,...,50,300,3738,66,0,high school,0,1,0,0
11,4777689a-5131,260000,2,1,2,51,-1,-1,-1,-1,...,8583,22301,0,3640,0,graduate school,1,0,0,0
12,b814ac5c-3d88,630000,2,2,2,41,-1,0,-1,-1,...,6500,6500,2870,0,0,university,0,0,0,1
13,a17b23d4-357b,70000,1,2,2,30,1,2,2,0,...,3000,3000,1500,0,1,university,0,0,0,1
14,0d6f99ad-84e9,250000,1,1,2,29,0,0,0,0,...,3000,3000,3000,3000,0,graduate school,1,0,0,0
15,8f023df0-a9ea,50000,2,3,3,23,1,2,0,0,...,1100,1200,1300,1100,0,high school,0,1,0,0
16,cbf648a6-98aa,20000,1,1,2,24,0,0,2,2,...,1500,0,1650,0,1,graduate school,1,0,0,0
17,cb258690-8ea2,360000,2,1,1,49,1,-2,-2,-2,...,0,0,0,0,0,graduate school,1,0,0,0
18,f6f0307a-b75f,180000,2,1,2,29,1,-2,-2,-2,...,0,0,0,0,0,graduate school,1,0,0,0
19,47a4cdaa-aa20,130000,2,3,2,39,0,0,0,0,...,1000,2000,930,33764,0,high school,0,1,0,0
20,834b2cac-750e,120000,2,2,1,39,-1,-1,-1,-1,...,0,632,316,0,1,university,0,0,0,1
21,c1d1d0f2-6aec,70000,2,2,2,26,2,0,0,2,...,0,3601,0,1820,1,university,0,0,0,1
22,66a293d5-6384,450000,2,1,1,40,-2,-2,-2,-2,...,560,0,0,1128,1,graduate school,1,0,0,0
23,817396f7-aad1,90000,1,1,2,23,0,0,0,-1,...,5398,1200,2045,2000,0,graduate school,1,0,0,0
24,275d9f10-f748,50000,1,3,2,23,0,0,0,0,...,1001,1432,1062,997,0,high school,0,1,0,0
25,7784e5a8-a66c,60000,1,1,2,27,1,-2,-1,-1,...,0,500,0,1000,1,graduate school,1,0,0,0
26,99ccbfaa-715b,50000,2,3,2,30,0,0,0,0,...,1000,1500,1000,1012,0,high school,0,1,0,0
27,72c682a7-c8af,230000,2,1,2,27,-1,-1,-1,-1,...,15339,14307,37292,0,0,graduate school,1,0,0,0
28,a8eb0be8-23bb,50000,1,2,2,33,2,0,0,0,...,1000,1000,1000,716,1,university,0,0,0,1
29,3b76b111-03c1,100000,1,1,2,32,0,0,0,0,...,3302,3204,3200,2504,0,graduate school,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26634,22a584bc-ac83,150000,1,4,2,31,2,0,0,0,...,0,0,0,0,1,others,0,0,1,0
26635,db2acf78-7f5d,20000,1,2,2,34,0,0,0,0,...,1000,5000,12914,600,0,university,0,0,0,1
26636,0b4f798d-f993,200000,1,2,1,33,0,0,0,0,...,2059,3000,9751,3000,0,university,0,0,0,1
26637,af452e9d-d287,360000,1,1,1,34,-1,-1,-1,0,...,8907,53,19584,16080,0,graduate school,1,0,0,0
26638,a381d0b4-087a,80000,1,3,1,36,0,0,0,0,...,2530,2556,3700,3000,0,high school,0,1,0,0
26639,a40d8b62-0083,190000,1,1,1,37,0,0,0,0,...,25128,10115,148482,4800,0,graduate school,1,0,0,0
26640,acdb424a-32bd,50000,1,2,1,37,1,2,2,2,...,0,0,1000,1000,1,university,0,0,0,1
26641,8dea83fa-2f50,40000,1,2,2,47,2,2,3,2,...,2000,0,3520,0,1,university,0,0,0,1
26642,f2df66b1-ef3b,420000,1,1,2,34,0,0,0,0,...,5500,5500,5600,5000,0,graduate school,1,0,0,0
26643,6c7190e2-b3fe,310000,1,2,1,39,0,0,0,0,...,10029,8049,8040,10059,0,university,0,0,0,1
26644,239a1d2e-f4f4,180000,1,1,1,32,-2,-2,-2,-2,...,0,0,0,0,0,graduate school,1,0,0,0
26645,2623fe20-6010,50000,1,3,2,42,0,0,0,0,...,5000,3000,4500,2000,0,high school,0,1,0,0
26646,af84788c-4c27,50000,1,2,1,44,1,2,2,2,...,0,517,503,585,0,university,0,0,0,1
26647,207df2a7-7dd6,90000,1,2,1,36,0,0,0,0,...,1500,1200,2500,0,1,university,0,0,0,1
26648,429d2c82-67ae,20000,1,2,1,44,-2,-2,-2,-2,...,2890,9263,1824,1701,0,university,0,0,0,1
26649,71ccca61-6306,240000,1,1,2,30,-2,-2,-2,-2,...,0,0,0,0,0,graduate school,1,0,0,0
26650,39b25a8c-193b,360000,1,1,2,35,-1,-1,-2,-2,...,0,0,0,0,0,graduate school,1,0,0,0
26651,aaf9f747-0646,130000,1,1,2,34,0,0,0,0,...,93000,4000,5027,4005,0,graduate school,1,0,0,0
26652,ef8a4bcd-79f3,250000,1,1,1,34,0,0,0,0,...,9011,6000,7000,6009,0,graduate school,1,0,0,0
26653,87388419-6a89,150000,1,1,2,35,-1,-1,-1,-1,...,783,0,0,0,0,graduate school,1,0,0,0
26654,33170a20-8592,140000,1,2,1,41,0,0,0,0,...,4228,1505,2000,2000,0,university,0,0,0,1
26655,46c706d6-6aef,210000,1,2,1,34,3,2,2,2,...,0,0,0,0,1,university,0,0,0,1
26656,4849f25c-3f1f,10000,1,3,1,43,0,0,0,-2,...,0,0,0,0,0,high school,0,1,0,0
26657,62c53ee3-f0cf,100000,1,1,2,38,0,-1,-1,0,...,4000,3000,2000,2000,0,graduate school,1,0,0,0
26658,67697c15-2247,80000,1,2,2,34,2,2,2,2,...,0,7000,0,4000,1,university,0,0,0,1
26659,ecff42d0-bdc6,220000,1,3,1,39,0,0,0,0,...,5003,3047,5000,1000,0,high school,0,1,0,0
26660,99d1fa0e-222b,150000,1,3,2,43,-1,-1,-1,-1,...,8998,129,0,0,0,high school,0,1,0,0
26661,95cdd3e7-4f24,30000,1,2,2,37,4,3,2,-1,...,22000,4200,2000,3100,1,university,0,0,0,1
26662,00d03f02-04cd,80000,1,3,1,41,1,-1,0,0,...,1178,1926,52964,1804,1,high school,0,1,0,0
26663,15d69f9f-5ad3,50000,1,2,1,46,0,0,0,0,...,1430,1000,1000,1000,1,university,0,0,0,1

In [ ]:
# Create features list

_____________________________________________________
**Next, make a 80:20 train/test split using a random seed of 24.**

_____________________________________________________
**Then, instantiate the `MinMaxScaler` to scale the data.**

_____________________________________________________
**Next, instantiate a logistic regression model with the `saga` solver, L1 penalty, and set `max_iter` to 1,000 as we want the solver to have enough iterations to find a good solution.**

_____________________________________________________
**Next, import the `Pipeline` class and create a `Pipeline` with the scaler and the logistic regression model, using the names `'scaler'` and `'model'` for the steps, respectively.**

_____________________________________________________
**Now, use the `get_params` method to view the parameters from each stage of the pipeline.**

In [ ]:
# Use `get_params`

**Use the `set_params` method to change the the `model__C` parameter to 2.**

In [ ]:
# View what `model__C` is set to currently

In [ ]:
# Change `model__C` to 2

_____________________________________________________
**Then, create a smaller range of C values to test with cross-validation, as these models will take longer to train and test with more data than our previous activities.**

**Use C_vals = [$10^2$, $10$, $1$, $10^{-1}$, $10^{-2}$, $10^{-3}$].**


<details>
    <summary>Hint:</summary>
    Recall that exponents in Python use the ** operator.
</details>

Now, define `k_folds` using `StratifiedKFold`. The number of folds should be 4. Set the random state to 1.

_____________________________________________________
**Next, make a new version of the `cross_val_C_search` function, called `cross_val_C_search_pipe`. Instead of the model argument, this function will take a pipeline argument. The changes inside the function will be to set the `C` value using `set_params(model__C = <value you want to test>)` on the pipeline, replacing the model with the pipeline for the fit and `predict_proba` methods, and accessing the `C` value using `pipeline.get_params()['model__C']` for the printed status update.**

_____________________________________________________
**Now, run this function as in the previous activity, but using the new range of `C` values, the pipeline you created, and the features and response variable from the training split of the case study data.**

    You may see warnings here, or in later steps, about the non-convergence of the solver; you could experiment with the `tol` or `max_iter`` options to try and achieve convergence, although the results you obtain with `max_iter = 1000` are likely to be sufficient.

_____________________________________________________
**Plot the average training and testing ROC AUC across folds, for each `np.log(C_vals)` value.**

_____________________________________________________
**Up next, create interaction features for the case study data using scikit-learn's `PolynomialFeatures`. You should use 2 as the degree of polynomial features. Confirm that the number of new features makes sense.**

_____________________________________________________
**Finally, repeat the cross-validation procedure and observe the model performance now.**

In [ ]:
# Using the new features, make a 80:20 train/test split using a random seed of 24.**

In [ ]:
# Call the cross_val_C_search_pipe() function using the new training data.
# All other parameters should remain the same.
# Note that this training may take a few minutes due to the larger number of features.

In [ ]:
# Plot the average training and testing ROC AUC across folds, for each C value.

**Take a look at the above graph. Does the average cross-validation testing performance improve with the interaction features? Is regularization useful?**